GET http://127.0.0.1:8000/api/categoria
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYzODIyOTcyMCwiZXhwIjoxNjM4MjMzMzIwLCJuYmYiOjE2MzgyMjk3MjAsImp0aSI6ImEzR0VmRVpvSnRFS0VZU2siLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.EWQcZS4N-lOK0KZq7dc3TZnBD-IZuWXjA8yP1SsUiV4

### Guardar Categoria
POST http://127.0.0.1:8000/api/categoria
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYzODIyOTcyMCwiZXhwIjoxNjM4MjMzMzIwLCJuYmYiOjE2MzgyMjk3MjAsImp0aSI6ImEzR0VmRVpvSnRFS0VZU2siLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.EWQcZS4N-lOK0KZq7dc3TZnBD-IZuWXjA8yP1SsUiV4

{
    "nombre": "PRUEBA"
}

### seleccionar la categoria y sus subcategorias

GET http://127.0.0.1:8000/api/categoria/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYzODIyOTcyMCwiZXhwIjoxNjM4MjMzMzIwLCJuYmYiOjE2MzgyMjk3MjAsImp0aSI6ImEzR0VmRVpvSnRFS0VZU2siLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.EWQcZS4N-lOK0KZq7dc3TZnBD-IZuWXjA8yP1SsUiV4


### Modificar Categoria
PUT http://127.0.0.1:8000/api/categoria/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYzODIyOTcyMCwiZXhwIjoxNjM4MjMzMzIwLCJuYmYiOjE2MzgyMjk3MjAsImp0aSI6ImEzR0VmRVpvSnRFS0VZU2siLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.EWQcZS4N-lOK0KZq7dc3TZnBD-IZuWXjA8yP1SsUiV4

{
    "nombre": "ROPA PARA DAMAS",
    "detalle": "Pruebaaaa"
}
